# Generated by Django 3.1.4 on 2020-12-16 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Employee1',
        ),
    ]
