# Generated by Django 3.1.4 on 2020-12-16 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicapp', '0002_auto_20201216_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetails1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('branch', models.CharField(choices=[('None', 'None'), ('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE')], max_length=4, null=True)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=10, null=True)),
                ('select_lang', models.CharField(choices=[('Telugu', 'Telugu'), ('Hindi', 'Hindi'), ('English', 'English')], max_length=10, null=True)),
                ('email', models.EmailField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('age', models.IntegerField(null=True)),
            ],
        ),
    ]
