# Generated by Django 3.1.4 on 2020-12-16 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicapp', '0003_studentdetails1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee1',
        ),
    ]
