# Generated by Django 3.1.4 on 2020-12-19 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicapp', '0006_auto_20201216_1555'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register',
            new_name='Register1',
        ),
        migrations.RenameModel(
            old_name='StudentDetails1',
            new_name='StudentDetails',
        ),
    ]
