# Generated by Django 3.1.4 on 2020-12-11 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ename', models.CharField(max_length=30)),
                ('Eid', models.CharField(max_length=20)),
                ('Esal', models.IntegerField()),
                ('mobile', models.CharField(max_length=10)),
                ('Email', models.CharField(max_length=30)),
                ('Eaddress', models.TextField(max_length=30)),
                ('Eresume', models.FileField(upload_to='path/')),
                ('Eimg', models.ImageField(upload_to=None)),
            ],
        ),
    ]
