# Generated by Django 3.1.4 on 2020-12-11 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0003_auto_20201211_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
    ]
