# Generated by Django 3.1.4 on 2020-12-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0006_studentnew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentnew',
            name='languages',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
